### ISSUE TITLE
2 Validation errors reports "Expected: object, given: null"

### ISSUE THREAD

**Issue by armab** [instrumenta/kubeval#102]
There is some disconnect between the linting validation based on API schema and the reality when `kubectl` accepts the objects, while `kubeval` can't validate them. As I understand that happens because K8s is laxed about some of the rules.

Here are examples found from adopting `kubeval` as a lint check tool [[ 1 ](https://github.com/StackStorm/stackstorm-enterprise-ha/pull/25)] [[ 2 ](https://circleci.com/gh/StackStorm/stackstorm-enterprise-ha/13)]: 

### configMap with null `data`
Validation:
```
The document ./templates/configmaps-rbac.yaml contains an invalid ConfigMap
---> data: Invalid type. Expected: object, given: null
```

Code: 
```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: RELEASE-NAME-test
data:   # <--- Validation ERROR
```

### volumeClaimTemplates with null `annotations` 
Validation: 
```
The document ./charts/rabbitmq-ha/templates/statefulset.yaml contains an invalid StatefulSet
---> spec.volumeClaimTemplates.0.metadata.annotations: Invalid type. Expected: object, given: null
The document ./charts/mongodb-ha/templates/mongodb-statefulset.yaml contains an invalid StatefulSet
---> spec.volumeClaimTemplates.0.metadata.annotations: Invalid type. Expected: object, given: null
```
Code: 
```yaml
---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  labels:
    app: mongodb-ha
    chart: mongodb-ha-3.5.3
    heritage: Tiller
    release: RELEASE-NAME
  name: RELEASE-NAME-mongodb-ha
spec:
  selector:
    matchLabels:
      app: mongodb-ha
      release: RELEASE-NAME
  serviceName: RELEASE-NAME-mongodb-ha
  replicas: 3
  template:
    metadata:
      labels:
        app: mongodb-ha
        release: RELEASE-NAME
      containers:
        - name: mongodb-ha
          image: "mongo:3.4"
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: datadir
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: datadir
        annotations:  # <-- Validation ERROR
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "10Gi"
```

Second case happen in official Helm Charts like [`mongodb-statefulset`](https://github.com/helm/charts/blob/d8bdbe1353c450aaa4fd832fb93a27c91332e1c6/stable/mongodb-replicaset/templates/mongodb-statefulset.yaml) and [`rabbitmq-ha`](https://github.com/helm/charts/blob/afe9cc0c764376c8a59316121274f92a68f806a4/stable/rabbitmq-ha/templates/statefulset.yaml).

From the Helm chart development standpoint using `kubeval` as a linting validation tool I think ideally is to keep it more practical so it could handle special lax cases, instead of just strictly following published API.
I have no idea if that's the direction behind the tool, but I think converging from strict API to what actually works in K8s will help with better adoption.
