### ISSUE TITLE
CronJob validation False positive

### ISSUE THREAD

**Issue by Hiruma31** [instrumenta/kubeval#103]
With for example a CronJob definition like
```
# kubetpl:syntax:go-template
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: test-cronjob
  namespace: {{ .namespace }}
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  schedule: 0 4 * * *
  successfulJobsHistoryLimit: 3
  suspend: false
  jobTemplate:
    spec:
      template:
        annotations:
          version: 1.0.0
        spec:
          containers:
          - command:
```

kubeval -v 1.8.2 passes.
```
The document stdin contains a valid CronJob
```
However, the spec.jobTemplate.spec.annotations is missing metadata so when applying, kubectl throw an error pointing out to the right syntax which would be spec.jobTemplate.spec.metadata.annotations
