### ISSUE TITLE
New master schemas disallow null values for lifecycle

### ISSUE THREAD

**Issue by tragiclifestories** [instrumenta/kubeval#118]
Hi there, we use kubeval to validate our YAMLs against master and we've been seeing failures suddenly. It seems that with the changes over the last day, the lifecycle property on containers and elsewhere has gone from missing a `type` field to having `"type": "object"`. 

This disallows null values, which however are valid (so far as I can tell) for a Kubernetes resource lifecycle.

**Comment by tragiclifestories** [comment]
Try this one:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: RELEASE-NAME-worker-default
  labels:
    app: team
spec:
  replicas: 10
  selector:
    matchLabels:
      app: team
      release: RELEASE-NAME
      role: worker
      worker: default
  template:
    metadata:
      labels:
        app: team
        release: RELEASE-NAME
        role: worker
        worker: default
    spec:
      containers:
        - name: app
          lifecycle: null
          image: eu.gcr.io/my-repo/dummy-repo:image-tag
          command: ["./start-worker"]
          args: []
          ports: []
          livenessProbe:
            exec:
              command:
              - ./check-worker-alive
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 1

          resources:
            limits:
              cpu: 500m
              memory: 256Mi
```

```
$ kubeval example.yaml
> The document example.yaml contains an invalid Deployment
> ---> spec.template.spec.containers.0.lifecycle: Invalid type. Expected: object, given: null
$ kubeval --kubernetes-version 1.13.0 example.yaml
> The document example.yaml contains a valid Deployment
```

But it should be the same for any resource whose spec contains a containers array with a `lifecycle: null` somewhere in there.
