### ISSUE TITLE
validation false positives if input is stdin

### ISSUE THREAD

**Issue by jkroepke** [instrumenta/kubeval#133]
Hi,

i'm running kubeval to validate my helm manifests.

While I'm testing with it I get errors with `binaryData` property via stdin.

Here is my configmap:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: init
  labels:
    app.kubernetes.io/component: keycloak
binaryData:
  mock-data.xls: "< ~200000 chars >"
```

Running `kubeval --strict init.yaml` works fine while `cat init.yaml | kubeval --strict` results into an error:

```
The document stdin contains an invalid ConfigMap
---> binaryData: Invalid type. Expected: object, given: null
```
