### ISSUE TITLE
It not validate spec names

### ISSUE THREAD

**Issue by RammusXu** [instrumenta/kubeval#162]
I write a wrong spec.`replicasss`. And it still showed `a valid Deployment`.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  labels:
    app: busybox
spec:
  replicasss: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:

      - name: busybox
        image: rammusxu/docker-box:python
        args: 
        - sh
        - -c
        - |
          tail -f /dev/null
```
## Expect
```
➜  action-demo git:(demo) ✗ docker run -it -v /Users/rammus/workspace/action-demo/kubernetes:/kubernetes garethr/kubeval -d kubernetes
The file kubernetes/break-folder/deployment-wrong.yaml contains an invalid Deployment
```
## Result
```
➜  action-demo git:(demo) ✗ docker run -it -v /Users/rammus/workspace/action-demo/kubernetes:/kubernetes garethr/kubeval -d kubernetes
The file kubernetes/break-folder/deployment-wrong.yaml contains a valid Deployment
```
