### ISSUE TITLE
improve validation of labels

### ISSUE THREAD

**Issue by mad01** [instrumenta/kubeval#207]
The issue. If you are for example adding a email address in a label that value will be invalid for example. If you run the validation it passes, but if you create or apply that manifest the server side validation in k8s will fail it since it's not following the naming standard. [ref](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set)

a valid label must be an empty string or consist of alphanumeric characters, '-', '' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue', or 'my_value', or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9.]*)?[A-Za-z0-9])?')

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: testing
  labels:
    owner: foo@example.com
```
