### ISSUE TITLE
Provide an --exclude command line argument to exclude some patterns or files

### ISSUE THREAD

**Issue by arthurlogilab** [instrumenta/kubeval#249]
Hey, kubeval looks really useful. We're adding it to our heptapod/gitlab CI. It's as simple as 

```
kubeval:
  image: garethr/kubeval
  script:
    - kubeval --directories .
```

We use kustomize https://kustomize.io/ so we have a bunch of `kustomization.yaml` which fail the test. Since we also store the resulting generated files in our repos, we'd like to be able to run `kubeval --directories . --exclude kustomization.yaml`

**Comment by arthurlogilab** [comment]
Our workaround for now is : 

```
kubeval:
  image: garethr/kubeval
  script:
    - rm */*/kustomization.yaml
    - kubeval --directories . 
```
