### ISSUE TITLE
Job and cronjob imagePullPolicy is not validated

### ISSUE THREAD

**Issue by agrounds** [instrumenta/kubeval#287]
The following is an invalid cronjob definition:
```yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: my-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          imagePullPolicy: Always
          containers:
            - name: busybox
              image: busybox:latest
              command: ["echo"]
              args: ["hello world"]
```
If I run `kubectl apply -f cj.yaml`, it returns
```
error: error validating "cj.yaml": error validating data: ValidationError(CronJob.spec.jobTemplate.spec.template.spec): unknown field "imagePullPolicy" in io.k8s.api.core.v1.PodSpec; if you choose to ignore these errors, turn validation off with --validate=false
```
However, `kubeval` doesn't catch the error
```
$ kubeval cj.yaml
PASS - cj.yaml contains a valid CronJob (my-cronjob)
```

The same applies to jobs. This invalid job definition also passes `kubeval`:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
spec:
  template:
    spec:
      imagePullPolicy: Always
      containers:
        - name: busybox
          image: busybox:latest
          command: ["echo"]
          args: ["hello world"]
```
