### ISSUE TITLE
Failed initializing schema ingress-networking-v1.json 404

### ISSUE THREAD

**Issue by dombisza** [instrumenta/kubeval#301]
hello there,
i was trying to validate ingresses, but I cannot do some because the schema URL gives me 404.
```
linux@sdombi-vpc-bastion:~$ cat ingress2.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /testpath
        pathType: Prefix
        backend:
          service:
            name: test
            port:
              number: 80
linux@sdombi-vpc-bastion:~$ kubeval ingress2.yaml
ERR  - ingress2.yaml: Failed initializing schema https://kubernetesjsonschema.dev/master-standalone/ingress-networking-v1.json: Could not read schema from HTTP, response status is 404 Not Found
linux@sdombi-vpc-bastion:~$ kubeval --version
Version: 0.16.1
Commit: f5dba6b486fa18b9179b91e15eb6f2b0f7a5a69e
Date: 2021-03-30T15:17:06Z
```
Am i doing something wrong here?
Thanks for the help in advance.
