### ISSUE TITLE
kubeval don't recognize extra field at root level

### ISSUE THREAD

**Issue by surajnarwade** [instrumenta/kubeval#34]
I have a file sample file as,

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    batman: true
    io.kompose.service: redis-master
  name: redis-master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: redis-master
    spec:
      containers:
      - image: gcr.io/google_containers/redis:e2e
        name: redis-master
        ports:
        - containerPort: 6379
      restartPolicy: Always
```

in which `batman` is extra key which kubeval recognize very well with strict mode,

```
$ kubval deployment.yaml --strict
The document redis-master-deployment.yaml contains an invalid Deployment
---> batman: Additional property batman is not allowed
```

But If I provide extra key `superman` at root level as below,

```
apiVersion: extensions/v1beta1
kind: Deployment
superman: true
metadata:
  labels:
    io.kompose.service: redis-master
  name: redis-master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: redis-master
    spec:
      containers:
      - image: gcr.io/google_containers/redis:e2e
        name: redis-master
        ports:
        - containerPort: 6379
      restartPolicy: Always
```

Kubeval fails to validate
```
$ kubval deployment.yaml --strict
The document redis-master-deployment.yaml contains a valid Deployment
```
