### ISSUE TITLE
Kubeval config file to reuse custom settings

### ISSUE THREAD

**Issue by lakhan-twilio** [instrumenta/kubeval#355]
Currently `kubeval` doesn't seem to have a config file via which we can configure its flag in a `yaml` or `json` file
Idea is to have `.kubeval.config.yaml` which can look like following
```yaml
k8s_version: string
strict_check: string || bool
force_color: string || bool
skip_kinds:
  - pod
  - deployment
  - service

openshift_schema: string || bool
schemas:
  k8s: 
    location: string
```
Obviously it can be improved in terms of structuring and we can add more flags as a configuration in this yaml file.
I hope you got the intent and idea for making it happen 👍
