### ISSUE TITLE
invalid service/deployment name passes kubeval

### ISSUE THREAD

**Issue by DamonStamper** [instrumenta/kubeval#70]
I ran a yaml file through kubeval and didn't get any errors. Later when I tried to apply the config to Minikube I got the below

```

Error from server (Invalid): error when creating "kubernetes.yaml": Service "Foo" is invalid: metadata.name: Invalid value: "Foo": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')

Error from server (Invalid): error when creating "kubernetes.yaml": Deployment.apps "Bar" is invalid: metadata.name: Invalid value: "Bar": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')

```

Changing the service/deployment `'metadata' > 'name'` per the errors allowed me to apply the yaml file to Minikube. 

Kubeval should check service/deployment configurations against the regex listed in the above error.

**Comment by garethr** [comment]
Could you include a failing definition file? I'll take a look at where this is failing.

kubeval relies exclusively on the Kubernetes OpenAPI descriptions, which might mean this information is missing from those. Or it could be a different local bug.

**Comment by DamonStamper** [comment]
Sure. Below is a failing example file.

```
apiVersion: v1
kind: Service
metadata:
  name: CapitalName
  labels:
    app: CapitalName
spec:
  selector:
    app: Invalid_App
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: underscore_name
  labels:
    app: underscore_name
spec:
  selector:
    app: underscore_name
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: 
  labels:
    app: Invalid_App
spec:
  template:
    metadata:
      labels:
        app: Invalid_App
    spec:
      containers:
      - name: CapitalName
        image: CapitalImage
        imagePullPolicy: Always
      - name: underscore_name
        image: underscore_image
        imagePullPolicy: Always
```

**Comment by iomv** [comment]
Based on this issue I have done some quick testing to check the level of validation it is performing and it seems that it is failing on a number of fronts: it might be checking the file schema, but arbitrary fields added to the file passed validation. E.g.:
```
apiVersion: extensions/v1beta1
kind: Deployment
spec:
  template:
    arbitrary: field
    another: one
    spec:
      containers:
      - env:
        image: ubuntu
        imagePullPolicy: Always
        name: ubuntu
        ports:
        - containerPort: 8100
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 300Mi
```

`kubeval  01_test.yaml' output:
The document 01_test.yaml contains a valid Deployment

`kubectl apply -f 01_test.yaml -dryrun` output
```error: error validating "01_test.yaml": error validating data: [ValidationError(Deployment.spec.template): unknown field "another" in io.k8s.api.core.v1.PodTemplateSpec, ValidationError(Deployment.spec.template): unknown field "arbitrary" in io.k8s.api.core.v1.PodTemplateSpec]; if you choose to ignore these errors, turn validation off with --validate=false```

Example with a service:
```
apiVersion: v1
kind: Service
```
`kubeval  02_test.yaml' output:
```The document 02_test.yaml contains a valid Service```
`kubectl apply -f 02_test.yaml -dryrun` output:
```error: error when retrieving current configuration of:
&{0xc42050a240 0xc420370d20 env-dev  05_test.yaml 0xc42158dcb0  false}
from server for: "02_test.yaml": resource name may not be empty```
