### ISSUE TITLE
Add support for Istio resources

### ISSUE THREAD

**Issue by grebois** [instrumenta/kubeval#80]
Considering this resource: 

```
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: default-pipeline-service
spec:
    destination:
      name: default-pipeline-service
    match:
        request:
          headers:
            uri:
              prefix: /api/
    rewrite:
        uri: /
---
```

I get:

```
2 errors occurred:

* Problem loading schema from the network at https://raw.githubusercontent.com/garethr/kubernetes-json-schema/master/master-standalone/routerule.json: Could not read schema from HTTP, response status is 404 Not Found
* Missing a kind key
```

This is the API reference: https://istio.io/docs/reference/config/istio.networking.v1alpha3/
